### ISSUE TITLE
Tools and Resources Page

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#71] opened 2017-08-23 15:46 UTC
Needs:

- [x] Page Design/Template

- [x] Content

- [ ] Implementation

**Comment by lfantano** [comment] 2017-08-23 15:48
Should include links to:

- JTR
- DTR
- Military 1 Source
- Military Installations
- Weight Calculator
- PPM Calculator
- Self Inventory form (PDF)
- Customer Service Page
- Locator Map Page
- Customs Forms necessary for OCONUS Moves
- Power of Attorney Template
- Portals for accessing orders

Anything else?

**Comment by Elliottdotgov** [comment] 2017-10-30 16:22
whoops, duplicate of https://github.com/deptofdefense/move.mil/issues/108

**Closed by Elliottdotgov** 2017-10-30 16:22 UTC
Labels: backlog, waiting on design
