### ISSUE TITLE
[IE10/11]: Army logo is off on service specific info page

### ISSUE THREAD

**Issue by Elliottdotgov** [deptofdefense/move.mil#246] opened 2017-12-12 15:22 UTC
link: https://www.move.mil/service-specific-information/army

tested with: https://netrenderer.com

Screenshot:
<img width="646" alt="screen shot 2017-12-12 at 10 18 38 am" src="https://user-images.githubusercontent.com/25456509/33892256-54c6b040-df26-11e7-906a-5701682eb021.png">

**Comment by aileendds** [comment] 2017-12-19 21:35
This is caused by https://github.com/deptofdefense/move.mil/commit/778ecef87af214d4b1e722e7174706462d8a599d and should be fixed once https://github.com/deptofdefense/move.mil/issues/254 is closed.

**Closed by aileendds** 2017-12-19 21:35 UTC
Labels: bug, internet explorer, up for grabs
