### ISSUE TITLE
Entitlements page: "Return to Top" navigation

### ISSUE THREAD

**Issue by jgarber623-gov** [deptofdefense/move.mil#78] opened 2017-08-28 14:06 UTC
## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [x] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

"Return to Top" button should be pinned to the right side of the browser.

## Observed Behavior

"Return to Top" button appears below the content area.

## Steps to Reproduce

To reproduce this issue…

1. Navigate to http://beta.move.mil/entitlements and
1. Observe position of "Return to Top" button.

## Screenshots

<img width="1097" alt="screen shot 2017-08-28 at 10 04 59 am" src="https://user-images.githubusercontent.com/27780860/29776964-63314e84-8bd8-11e7-9d51-024471747291.png">

**Comment by aileendds** [comment] 2017-11-06 15:42
This is now a duplicate of https://github.com/deptofdefense/move.mil/issues/120

**Closed by aileendds** 2017-11-06 15:42 UTC
Labels: enhancement
