### ISSUE TITLE
Request creation of a search block

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#412] opened 2018-04-04 15:52 UTC
Request creation of a search block so that customers can search the site using key words that bring up a list so customers can narrow down what they are looking for instead of having to search through each tab in order to find things quickly.

The below screenshot is an idea for the location of the search box.

[Search.docx](https://github.com/deptofdefense/move.mil/files/1876279/Search.docx)

**Comment by jgarber623-gov** [comment] 2018-04-09 13:30
@robert078 Thanks for filing this issue! It appears to be a duplicate of #311. Would you agree? If so, could you post your comment and screenshot there so we can track progress?

**Comment by jgarber623-gov** [comment] 2018-04-10 12:32
@jillesmith1 Works for me! Closing as a duplicate of #311. We'll track work over there.

**Closed by jgarber623-gov** 2018-04-10 12:32 UTC
Labels: question, ustc reviewed
