### ISSUE TITLE
Nightmare moves page

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#67] opened 2017-08-23 15:40 UTC
Needs: 

- [ ] Page Design
- [x] Content (created in several locations, needs aggregated?)
- [ ] Implementation

**Comment by jde1984** [comment] 2017-08-23 16:52
[Nightmare Moves.docx](https://github.com/deptofdefense/move.mil/files/1246250/Nightmare.Moves.docx)

Nightmare moves... not sure how many of these we wanted or how in depth... I tried to pull out the key points to highlight lessons learned.  Let me know if you want more - happy to add more but I was told by designers the rule of 3 typically applies...

**Comment by jgarber623-gov** [comment] 2017-09-11 14:44
@jde1984 @lfantano Leaving out this line from the content until we sort out setting up email address and/or contact forms:

> If you have a nightmare move to suggest, please submit to nightmaremoves@move.mil. We love getting tips you can share with your fellow service members.

**Comment by jgarber623-gov** [comment] 2017-09-11 14:49
Initial content entered, resolving this issue as of 64e542b.

**Closed by jgarber623-gov** 2017-09-11 14:49 UTC
Labels: help wanted, waiting on design
